from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class Intent(str, Enum):
    INVENTORY_STATUS = "inventory_status"
    INVENTORY_RISK = "inventory_risk"
    PO_DELAY = "po_delay"
    PERFORMANCE = "performance"
    HEALTH = "health"
    OPPORTUNITY = "opportunity"
    SCENARIO_COMPARE = "scenario_compare"
    RAG_LOOKUP = "rag_lookup"
    SHIPMENT_STATUS = "shipment_status"
    GENERAL_CHAT = "general_chat"
    CLARIFICATION = "clarification"

class EntityType(str, Enum):
    MATERIAL = "material"
    SKU = "sku"
    CATEGORY = "category"
    WAREHOUSE = "warehouse"
    PLANT = "plant"
    PO = "purchase_order"
    SUPPLIER = "supplier"
    SHIPMENT = "shipment"
    TIME_PERIOD = "time_period"

class ExtractedEntity(BaseModel):
    entity_type: EntityType
    value: str
    original_text: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)

class QueryUnderstandingResult(BaseModel):
    normalized_query: str
    primary_intent: Intent
    secondary_intents: List[Intent] = Field(default_factory=list)
    entities: List[ExtractedEntity] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)
    requires_clarification: bool = False
    clarification_question: Optional[str] = None
    is_degraded: bool = False  # True if generated by fallback classifier

class ToolCall(BaseModel):
    tool_name: str
    arguments: Dict[str, Any] = Field(default_factory=dict)
    rationale: Optional[str] = None

class QueryPlan(BaseModel):
    steps: List[ToolCall] = Field(default_factory=list)
    requires_rag: bool = False
    rag_query: Optional[str] = None
    fallback_to_general: bool = False

class GroundedResponse(BaseModel):
    content: str
    suggested_actions: List[str] = Field(default_factory=list)
    sources: List[str] = Field(default_factory=list)
    data_points: List[Dict[str, Any]] = Field(default_factory=list)
